services:
  - type: web
    name: clusterflow-api
    env: python
    region: oregon
    buildCommand: pip install fastapi uvicorn[standard] pydantic joblib numpy scikit-learn kmodes
    startCommand: cd Clusterflow/backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
